name: PreMerge Build

on:
  pull_request:
    branches:
      - main  # PRのターゲットブランチがmainの場合に動作する

jobs:
  pre-merge-build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '23'

      - name: Install frontend dependencies
        run: cd frontend && npm install

      - name: Build the project
        run: cd frontend && npm run build

      - name: Run frontend lint
        run: cd frontend && npm run lint

      - name: Install backend-ts dependencies
        run: cd backend-ts && npm install

      - name: Run backend-ts lint
        run: cd backend-ts && npm run lint
      
      - name: Install cdk-ts dependencies
        run: cd cdk-ts && npm install

      - name : Run cdk-ts lint
        run : cd cdk-ts && npm run lint
